version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - web
    # volumes:
    #   - ./app:/app/app  # Hot reload pour le développement

  db:
    image: postgres:16
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=school_attendance
      - POSTGRES status_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume persistant
      - ./backups:/backups  # Dossier pour les sauvegardes
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - web

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080" 
    networks:
      - web

networks:
  web:

volumes:
  postgres_data: