FROM python:3.11-slim

WORKDIR /app

# Installer uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copier les fichiers de projet
COPY pyproject.toml ./
COPY app/ ./app/
COPY tests/ ./tests/

# Installer les dépendances
# RUN uv sync --frozen --no-dev --group test

# Installer les dépendances principales
RUN uv pip install --system -r pyproject.toml

# Installer les dépendances de test (optionnelles)
RUN uv pip install --system ".[test]"


# Exécuter les tests
CMD ["uv", "run", "pytest", "tests/", "-v", "--cov=app"]