# Configuration de bumpversion
[bumpversion]
current_version = "0.0.0"
commit = True
tag = True
parse = (?P<major>\d+)\.(?P<minor>\d+)(\.dev(?P<dev>\d+))?
serialize =
    {major}.{minor}.{patch}.dev{dev}
    {major}.{minor}.{patch}

[bumpversion:part:release]
optional_value = release
values =
    .dev
    release

# Configuration de Tox
[tox]
isolated_build = true
envlist = py310,py311

[testenv]
skipsdist = true
allowlist_externals = uv
skip_install = true
description = run the tests with pytest
commands =
    uv run ruff check --fix
    uv run pycodestyle --ignore E501 --show-pep8 --statistics app tests
    uv run flake8 --ignore E501 app tests
    uv run isort --check-only --diff --up app tests
    uv run pylint --rcfile=pylint.rc app tests --disable=C0116,C0115,C0114
    #uv run pytest -m integration
    #uv run pytest -m 'unit or component'

setenv =
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LC_ALL=en_US.UTF-8

[testenv:integration]
allowlist_externals = uv
commands = uv run pytest -m integration

[testenv:type]
deps = mypy
commands = uv run mypy --ignore-missing-imports --no-warn-no-return --install-types --non-interactive app tests

# Configuration pour pycodestyle
[pycodestyle]
max-line-length = 100

# Configuration pour isort
[isort]
force_grid_wrap = 0
use_parentheses = False
multi_line_output = 0
line_length =

# Configuration pour pytest
[pytest]
junit_family = legacy
addopts = -v \
          --junit-xml=report/tests-report.xml \
          --cov=app \
          --cov-report=xml:report/coverage-report.xml \
          --cov-report=html:report/report.html \
          --cov-config=.coveragerc

markers =
    unit: mark a test as a unit test.
    component: mark a test as a component test.
    integration: mark a test as an integration test.
    smoke: mark a test as a smoke test.

# Configuration pour flake8
[flake8]
show-source = True
exclude = .git/,config/,__pycache__,venv,.env
ignore = F401,F403,F405
max-line-length = 150

# Configuration pour la couverture de code
[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    if self\.debug
    raise AssertionError
    raise NotImplementedError
    if 0:
    if __name__ == '__main__':

show_missing = True

# Configuration pour la génération de rapports HTML
[coverage:html]
directory = coverage_html_report
